### ISSUE TITLE
I got wrong training results

### ISSUE THREAD

**Issue by zgxiangyang** [pfnet-research/sngan_projection#12]
I used data from ILSVRC2017_DET.tar.gz, 

choosed ILSVRC/Data/DET/train/ILSVRC2013_train

and prepossessed it as described.

But I got following preview results after 130000 iterations' training.

![image](https://user-images.githubusercontent.com/4465386/39683847-5c7ddf66-51ea-11e8-8341-85d76034c411.png)

**Comment by takerum** [comment]
The dataset you chose is the detection dataset and our preprocessing script does not support it.
Does `/ILSVRC/Data/CLS-LOC/train/` exist in your ILSVRC dataset? That is the one we used for the experiments.

**Comment by zgxiangyang** [comment]
@takerum Thank you. I will try to use CLS-LOC data. 
I only used 3 classes before. 
After I added more classes and change n_classes:1000 to 569 in "sn_projection_.yml"  (I didn't changed this param before) , it produced several colorful meaningful images now.
