### ISSUE TITLE
How Lipchitz Constant is limited in Resblock?

### ISSUE THREAD

**Issue by hlqwerty** [pfnet-research/sngan_projection#14]
In the resblock structure f, the function could be written as f(x)=W(a(W(a(x))))+x.
The Lipchitz of f can be controlled as ||f||_Lip < ||W||||a||||W||||a||+1. When we adopt SN for W, it seems that ||f||_Lip could be controlled by 2. So the Lipchitz of discriminator grows exponentially through every block.

I'm really confused about this problem, thanks!

**Comment by takerum** [comment]
Thanks for your comment!

Yes, you are right.
The bound on the Lipschitz constant will exponentially grow when you apply SN on resblock.
But in that case, the Lipschitz constant is still bounded by some constant (maybe 2^L) if the number of resblock layers L is finite.
The essence of SN is adding a Lipschitz constraint on the discriminator, and the designated value of the Lipschitz constant is a hyper-parameter. 
In the paper, we set the value to 1 for simplicity, but you can control it by multiplying some constant after each layer.

**Comment by hlqwerty** [comment]
It's clear to me now. Thank you so much!
