### ISSUE TITLE
Tensorflow implementation / advice for SNEmbed_Id layer

### ISSUE THREAD

**Issue by anshkapil** [pfnet-research/sngan_projection#16]
Hello all,

Does somebody have the code for tensorflow implementation of SNEmbedId layer?
Or can somebody advice what embedding method to use with tensorflow to create this SN Embedding layer?

Thanks,
Ansh

**Comment by takerum** [comment]
You can use tf.nn.embedding_lookup:
```
def SNEmbedID(y):
  emb = (spectrally normalized embedding weight, maybe you can use this:https://github.com/minhnhat93/tf-SNDCGAN/blob/master/libs/sn.py#L12) 
  return tf.nn.embedding_lookup(emb, y)
```
