### ISSUE TITLE
training for STL-10 dataset

### ISSUE THREAD

**Issue by youkaichao** [pfnet-research/sngan_projection#20]
could you please add the code for training STL-10 dataset?

I notice that in your paper, STL-10 has very high inception score, and models trained on STL-10 have much lower score. 

I wonder how you test the inception score. STL-10 has data with labels and data without labels, do you use the labeled data to test the inception score or unlabled data? or both? And in your training, what data do you use? Both or labeled only or unlabeled?

I want to reproduce the result in your paper so I want to know some details ^_^

**Comment by takerum** [comment]
We only used the unlabeled set for the experiments on STL-10.
I will release the code on STL-10 if you still are in trouble on reproducing the results.

**Comment by kracwarlock** [comment]
@takerum Is it possible for you to share the config file for STL-10?
