### ISSUE TITLE
Cant reproduce the results in the papers

### ISSUE THREAD

**Issue by zgxiangyang** [pfnet-research/sngan_projection#21]
I used imagenet data 'ILSVRC2012_img_train', which is used for image detection in general.
After 384000 iterations, the "inception_mean" was still 16.8.
I used the same config file as "configs/sn_projection.yml", Should I change 'augmentation' to 'true' or something else need to be changed.

**Comment by takerum** [comment]
The settings in `configs/sn_projection.yml` are used for the experiments in the ICLR papers, so you don't need to change anything.

You might use a different dataset from what we used in our experiments. 
Could you tell me the URL where I can download the dataset? I will check it.

**Comment by takerum** [comment]
The hyper-parameters in `configs/sn_projection.yml` are the ones we used for the experiments in the ICLR papers, so you don't need to change anything.

You might use different ImageNet dataset from the dataset we used.
Could you tell me the URL where I can download the dataset you are using? I will check it.

**Comment by zgxiangyang** [comment]
@takerum I downloaded it from here, http://academictorrents.com/details/a306397ccf9c2ead27155983c254227c0fd938e2

And now after 800000 iterations, the "inception_mean" is 22.
I used train.py rather than train_mn.py, and the batchsize is 16 as the same with your file.
Should this be the problem?

**Comment by takerum** [comment]
Yes, the scores in the paper were produced with the batchsize of 64. 
the batchsize in each `.yml` files specifies the number of samples per 1 GPU, and we assume `configs/sn_projection.yml` is used under 4GPUs environment.
