### ISSUE TITLE
How to generate images with 256 resolution?

### ISSUE THREAD

**Issue by NeuralBricolage** [pfnet-research/sngan_projection#27]
i was successful with generating images with 128 res and 15 classes training on my own datasets. Now i'd like to try 256 res and i changed size in the config and dataset class from 128 to 256, also scaled up G and D from small to resnet. but the preview file (image_latest.png) is still has 128X128 and now i'm not sure where to look. Any suggestions please?

thanks much!

if it matters i'm training on GTX 1080TI - hopefully it's sufficient (i suppose i can decrease the batchsize too)

**Comment by takerum** [comment]
Hmm, that's strange. The code which generates `image_latest.png` specifies its resolution from the generated images:
https://github.com/pfnet-research/sngan_projection/blob/master/evaluation.py#L61. 
Could you make sure that the resolution of generated images is actually 256?

**Comment by NeuralBricolage** [comment]
thank you for your response - reran it again - H,W are printed out as 128, 128 which is not surprising considering this is what is in the image_latest mosaic... :(

**Comment by NeuralBricolage** [comment]
perhaps if you could add a yaml sample for 256X256, would it be possible? or maybe some code needs to be changed too?
thank you!

**Comment by takerum** [comment]
I uploaded the config file that I used for training the 256px models on dog and cat ImageNet.
https://github.com/pfnet-research/sngan_projection/blob/master/configs/sn_projection_dog_and_cat_256.yml
I ran with the config on 8GPUs environment, so maybe you need to change the channel sizes of G and D and the batchsize in order to fit 1GPU training.

**Comment by NeuralBricolage** [comment]
thank you so much, i will give this a try!
