### ISSUE TITLE
Pre Trained model for the discriminator

### ISSUE THREAD

**Issue by AdvaitGadhikar** [pfnet-research/sngan_projection#28]
I wanted to ask if you can provide the pre trained Discriminator model as well.

**Comment by takerum** [comment]
sorry for the delayed response. 
I have uploaded the pretrained discriminators here: https://drive.google.com/drive/folders/1xZoL48uFOCnTxNGdknEYqE5YX0ZyoUej?usp=sharing
If you see any problems, please let me know.
