### ISSUE TITLE
Initialization for res_blocks

### ISSUE THREAD

**Issue by tatajack** [pfnet-research/sngan_projection#29]
Hi, I'd like to know if there's a particular reason for using **glorot_uniform** as the initializer of ResBlocks?
As far as I know, ResBlocks are known to work well with **he_normal** initialization.

**Comment by takerum** [comment]
just followed the network implementation used in the original WGAN-GP paper: https://github.com/igul222/improved_wgan_training

**Comment by tatajack** [comment]
I see. Thanks for the explanation.
