### ISSUE TITLE
equation on your paper cGans with Projection Discriminator

### ISSUE THREAD

**Issue by Paseam** [pfnet-research/sngan_projection#3]
after read your paper, I'm confused about how to get equation 2 from equation 1 in your paper? can you give me some suggestions

**Comment by takerum** [comment]
Sorry for the delayed response.
Please remember that when we maximize E_q(x) [log D(x)] + E_p(x) [log(1-D(x)] w.r.t D(x) := \sigmoid(f(x)) = 1/(1+exp(-f(x)), we get D*(x) = q(x) / (q(x) + p(x)) .
Then, we get f*(x) = log (q(x) / p(x)) by solving q(x) / (q(x) + p(x)) =  1/(1+exp(-f*(x)) for f*(x).
