### ISSUE TITLE
Clarification needed between the paper and the code for cifar10

### ISSUE THREAD

**Issue by youngjung** [pfnet-research/sngan_projection#51]
Hi, thanks for sharing nice work.

Could you clarify which one is correct between the paper and the code for cifar10?

The paper describes different number of channels through layers(64, 128, 256, 512) but the code uses the same number of channels(128s).

Paper:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/45905238/56709772-092c5d80-675e-11e9-8131-0ae9feae8562.png">

Code:
https://github.com/pfnet-research/sngan_projection/blob/e84b1a5f604de5fec268f37c3f26478e80b7f475/dis_models/snresnet_32.py#L8-L19

**Comment by takerum** [comment]
Table 3 and 4 show StandardCNN and ResNet architectures used in our experiments.
We only uploaded the ResNet architecture code as `snresnet_32.py`. You can find the Standard CNN architecture code is here: https://github.com/pfnet-research/chainer-gan-lib/blob/master/common/net.py#L55  https://github.com/pfnet-research/chainer-gan-lib/blob/master/common/net.py#L199.

**Comment by youngjung** [comment]
Oh, now I see the notation. Thanks!
