### ISSUE TITLE
Should I apply only to the discriminator?

### ISSUE THREAD

**Issue by taki0112** [pfnet-research/sngan_projection#7]
Should I apply only to the discriminator?

Do not apply spectral normalization to both generator and discriminator?

**Comment by takerum** [comment]
No problem for applying spectral normalization to both, but we have not tried that.

**Comment by taki0112** [comment]
Do you think it would help to apply to both generator and discriminator?

Or do you think it's better to apply only to discriminator?

**Comment by takerum** [comment]
Sorry, I am not sure.

**Comment by takerum** [comment]
Sorry, I am not sure.
I think there is no obvious reason that we need to constrain the Lipschitz constant of the generator, thus I recommend to apply SN only to discriminator
