### ISSUE TITLE
Is it image translation ? 

### ISSUE THREAD

**Issue by taki0112** [pfnet-research/sngan_projection#8]
![image](https://user-images.githubusercontent.com/26713992/38418829-fabff2ba-39d8-11e8-9c40-e4dfaae559ee.png)

In the above results, you converted the image from dog to cat,
It is very good...

Using CycleGAN? What is this?

**Comment by takerum** [comment]
Hi, thanks for your comment.

These are images generated with varying the category embedding of conditional BN in the generator.
The embedding for each image is calculated by the weighted sum of 4 different category embeddings.
