### ISSUE TITLE
SNGAN + Projection Discriminator is amazing

### ISSUE THREAD

**Issue by hubert0527** [pfnet-research/sngan_projection#9]
Just a comment confirming these two works (SN and projection discriminator) are just amazing!

I am working on a new application of GANs. I've tried ACGAN for a half-month hardworking but the quality of results are steadily awful. After changing the architecture of discriminator (already with SN) to Projection Discriminator, the generated results simply bumped to the next generation.

This is really a nice work/project with clean code! 
Thanks for author's sharing :)

**Comment by takerum** [comment]
Thanks for your comment, and I am very happy to hear that!
